# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_part', '0007_article_name1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name1111',
            new_name='name',
        ),
    ]
