# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_part', '0008_auto_20171115_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
    ]
