# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatic_part', '0003_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='automatic_article',
        ),
    ]
