# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linux_part', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('type', models.CharField(default=None, max_length=10)),
                ('time', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
    ]
